### ISSUE TITLE
Cannot send back the annotations to OMERO server

### ISSUE THREAD

**Issue by Guikkz** [qupath/qupath-extension-omero-web#20]
Hello,
First of all thank you for the amazing software !
I am able to connect my OMERO server (5.13)<`https://my.omero.server`> to my QuPath (0.3.2) through the OMERO extension (0.3.0.jar), browse through all datasets and add images to projects.
Unfortunately, when I try to use the send annotations to OMERO the process start with some confirmation message but fail with this message:
`ERROR: Could not send object: <https://my.omero.server>/iviewer/persist_rois/`

Could you help me sort this out ?
Best regards,
Guikks

**Comment by petebankhead** [comment]
Hi @Guikkz I'd recommend posting your question on the forum at https://forum.image.sc/tag/qupath

More people who use OMERO and QuPath together may see it there - and you can use both `OMERO` and `qupath` as tags on your post.

**Comment by petebankhead** [comment]
Discussion is at https://forum.image.sc/t/cannot-send-back-the-annotations-from-qupath-to-omero-server/69690
