### ISSUE TITLE
OME.TIFF not recognized as a valid image format, by QuPath Extension.

### ISSUE THREAD

**Issue by raymond301** [qupath/qupath-extension-omero-web#23]
I have OME.TIFF images that I can load into QuPath, and that can also be loaded in OMERO (internal server)...however this extension between those two software does not recognize those images as being able to pull from OMERO to QuPath.

Here is a screenshot of what I am able to see. Specific text is blurred out to protect project & PI names.
![ScreenShot2022-09-15](https://user-images.githubusercontent.com/392344/190456611-58716bfb-0707-4c54-bbb3-5ddb2013f957.png)

**Comment by petebankhead** [comment]
The extension uses the web API, so is limited to JPEG-compressed RGB images. There's a comment about it in the readme here, but I'm not sure we've described that (major!) limitation in the documentation... so we really should.

The image in your link is 16-bit, so raw pixel access is needed. That's not straightforward to achieve, but it's the topic of
* https://github.com/qupath/qupath-extension-omero/issues/21

**Comment by raymond301** [comment]
I see.
That is unfortunate. My institution is primarily interested in using OMERO & QuPath for MxIF images...thus making this a pretty significant hurdle. We've already archived a good adoption rate for QuPath, via OME.TIFF on network drives, and the hope was to further enhance usage with a web-based project storage & managements system. 
If this door is truly closed, then I will begin searching for that open window. Thank you.
